application: myflaskonappengineapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "5d"

builtins:
- appstats: on
- admin_redirect: on
- deferred: on
- remote_api: on

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

inbound_services:
- warmup

handlers:
- url: /favicon.ico
  static_files: application/static/img/favicon.ico
  upload: application/static/img/favicon.ico

- url: /robots.txt
  static_files: application/static/robots.txt
  upload: application/static/robots.txt

- url: /gae_mini_profiler/static
  static_dir: packages/gae_mini_profiler/static

- url: /gae_mini_profiler/.*
  script: packages.gae_mini_profiler.main.application

- url: /_themes/(.*)/(.*)
  static_files: application/themes/\1/static/\2
  upload: application/themes/(.*)/static/(.*\.(gif|png|jpg|css|js))

- url: /static/cdn/.*
  script: runner.app

- url: /static
  static_dir: application/static

- url: .*
  script: runner.app
