version: 1

formatters:
  brief:
    format: "%(levelname)-8s: %(message)s"
  precise:
    format: "%(asctime)s %(filename)s:%(lineno)d\n  %(levelname)-8s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: brief
    stream: ext://sys.stdout

root:
  level: DEBUG
  handlers: [console]

...
